### ISSUE TITLE
Build initial python-flask app

### ISSUE THREAD

**Issue by elleanne** [kescardoso/datasetbucket#1]
Build the initial app with flask. 
Ensure that we can parse files well with flask

**Comment by kescardoso** [comment]
👍🏻  The basic app structure is now completed!

![](https://media4.giphy.com/media/l3nWmPFBffbkCd3Ow/giphy.gif)

**Comment by kescardoso** [comment]
👍🏻  The basic app structure is now ready for other team members to play with!
@eliboss @sakshigupta265 @wyang0216 

Apart from all the data already being handled in the current app version, **file parsing functionality** will have to be sorted using JSON (MongoDB is not hyperlink or file friendly).

All details for the latest PR can be found here:
https://github.com/kescardoso/datasetbucket/pull/8

### List of Features:

**Added**
- Data-bonded dataset collapsible list (view and manage)
- Data-bonded register, login, logout and user session
- Data-bonded edit (update) and add (insert) new dataset
- Responsive design
- Form validation
- Activity alerts and confirmations with tooltips and flash message
- User privileges

**Left to be implemented**
(Non-urgent) will be implemented shortly during week#2:
- Dataset Categories : List and manage
- Dynamic Search
- Pagination
- Footer

**Further Optional or Advanced Features**
- Better UX/UI/Design rules
- More info/functionalities for user profile
- About and Home page
- User session tag (menu)

### What's Next
The app is ready to be tested!
Instructions for local Installation: 
https://github.com/kescardoso/datasetbucket/wiki/Instructions:-Local-Installation
I will be sending sensitive information via Discord for your local installation and deployment.
I encourage all team members to register and create their own unique account via the heroku deployed version to unveil user privileges. Have fun!

![](https://media4.giphy.com/media/l3nWmPFBffbkCd3Ow/giphy.gif)
